default_context:
    author_name: "Eva Maxfield Brown, To Huynh, Isaac Na, Council Data Project Contributors"
    author_email: "evamaxfieldbrown@gmail.com"
    hosting_github_username_or_org: "CouncilDataProject"
    project_name: "cdp-backend"
    project_slug: "cdp-backend"
    python_slug: "cdp_backend"
    project_short_description: "Data storage utilities and processing pipelines used by CDP instances."
    hosting_pypi_username: "CouncilDataProject"
    license: "Apache v2 License"