name: Check Pull Request

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install graphviz (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install graphviz
    - name: Install graphviz (Mac)
      if: matrix.os == 'macOS-latest'
      run: |
        brew install graphviz
    - name: Install graphviz (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install graphviz
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest --cov-report xml --cov=cdp_backend cdp_backend/tests/
    - name: Upload Codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install graphviz
      run: |
        sudo apt-get install graphviz
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 cdp_backend --count --verbose --show-source --statistics
    - name: Check imports with isort
      run: |
        isort cdp_backend --check-only
    - name: Check typing with mypy
      run: |
        mypy cdp_backend
    - name: Check with black
      run: |
        black --check cdp_backend

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install graphviz
      run: |
        sudo apt-get install graphviz
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Generate Docs
      run: |
        make gen-docs
