name: Check Pull Request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest --cov-report xml --cov=cdp_backend cdp_backend/tests/
    - name: Upload Codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 cdp_backend --count --verbose --show-source --statistics
    - name: Check with black
      run: |
        black --check cdp_backend

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install graphviz
      run: |
        apt-get install graphviz -y
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Generate Docs
      run: |
        make gen-docs
