name: Check Pull Request

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt-get install graphviz --fix-missing
        sudo apt-get install ffmpeg --fix-missing
    - name: Install Packages (Mac)
      if: matrix.os == 'macOS-latest'
      run: |
        brew install graphviz
        brew install ffmpeg
    - name: Install Packages (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install graphviz
        choco install ffmpeg
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Run tests with Tox
      run: tox -e py
    - name: Upload Codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install graphviz
      run: |
        sudo apt update
        sudo apt-get install graphviz --fix-missing
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Lint
      run: pre-commit run --all-files --show-diff-on-failure

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install graphviz
      run: |
        sudo apt update
        sudo apt-get install graphviz --fix-missing
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Generate Docs
      run: |
        make gen-docs
