name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt-get install graphviz --fix-missing
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          just install
      - name: Generate Docs
        run: |
          just generate-docs
          touch docs/_build/.nojekyll
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/
